package pimms.oblig2.graphics;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;

import android.content.Context;
import android.content.res.AssetManager;
import android.nfc.FormatException;
import android.util.Log;

/*
 * Class to load Polygon File Format files.
 * 
 * It's very important to notice that not all PLY-files
 * are possible to load. This implementation primarily
 * focuses on supporting PLY-files generated by Blender.
 * 
 * Some assumptions regarding input files:
 * 	1.	XYZ is the only valid order for axes. 
 * 		"YXZ", "XY", "Z" and similar are NOT supported.
 * 		
 * 	2.	All vertex data must be bundled. Normals and texture 
 * 		coordinates must be defined in the same list as vertices.
 * 		Vertex indices 
 * 
 *  3.	Types are ignored, and casted to float .
 */
public class ObjLoader {
	private static final String TAG = "3dOBJ";
	private Scanner mFileScanner;
	
	// TODO:
	// Conversion to a single array is inefficient.
	// If time allows it, improve this.
	private ArrayList<float[]> mVertices;
	private ArrayList<int[]> mFaces;
	
	public ObjLoader() {
		mVertices = new ArrayList<float[]>();
		mFaces = new ArrayList<int[]>();
	}
	
	public boolean parseFile(String fileName, Context context) {
		// hehehehehehehehehehehehehehehe 
		AssetManager assManager = context.getAssets();
		
		try {
			mFileScanner = new Scanner(assManager.open(fileName, AssetManager.ACCESS_STREAMING));
		} catch (Exception ex) {
			Log.e(TAG, "Failed to open file " + fileName);
			return false;
		}
		
		try {
			while (mFileScanner.hasNextLine()) {
				parseLine();
			}
		} catch (FormatException e) {
			Log.e(TAG, "Invalid format in OBJ-file.");
			return false;
		}
		
		return true;
	}
	
	public float[] getVertices() {
		// drawElements is not currently supported. Generate an 
		// array containing redundant elements ready to be drawn
		// using drawArrays.
		
		// Calculate the total amount of vertices
		int length = 0;
		for (int i=0; i<mFaces.size(); i++) {
			length += mFaces.get(i).length;
		}
		
		float[] verts = new float[length * 3];
		
		// Build our newly created (and ridonculously awesome) array
		int idx = 0;
		for (int i=0; i<mFaces.size(); i++) {
			int[] face = mFaces.get(i);
			
			for (int j=0; j<face.length; j++) {
				float[] vert = mVertices.get(face[j]);
				for (int k=0; k<3; k++) {
					verts[idx++] = vert[k];
				}
			}
		}
		
		return verts;
	}
	
	public int[] getIndices() {
		return null;
	}
	
	public float[] getTexCoords() {
		return null;
	}
	
	
	private void parseLine() throws FormatException {
		String next = mFileScanner.next();
		
		if (next == "v") {
			parseVertex();
		} else if (next == "f") {
			parseFace();
		} else {
			// Discard the line
			mFileScanner.nextLine();
		}
	}
	
	private void parseVertex() throws FormatException {
		String line = mFileScanner.nextLine();
		String[] elems = line.split(" ");
		
		if (elems.length != 3) {
			throw new FormatException("Expected 3 vertex elements, got " + elems.length);
		}
		
		float[] vert = new float[3];
		for (int i=0; i<3; i++) {
			vert[i] = Float.parseFloat(elems[i]);
		}
		
		mVertices.add(vert);
	}
	
	private void parseFace() throws FormatException {
		String line = mFileScanner.nextLine();
		String[] indices = line.split(" ");
		
		if (indices.length < 3) {
			throw new FormatException("Very unable to build a face from <3 vertices");
		}
		
		int[] face = new int[indices.length];
		for (int i=0; i<indices.length; i++) {
			face[i] = Integer.parseInt(indices[i]);
		}
		
		mFaces.add(face);
	}
}
































